/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#006e4b",
        "surface-tint": "#4d44e3",
        "primary": "#3525cd",
        "tertiary-fixed": "#6ffbbe",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed": "#e2dfff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-container": "#4f46e5",
        "secondary-container": "#d0e1fb",
        "on-tertiary-container": "#67f4b7",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e0e3e5",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "outline-variant": "#c7c4d8",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#005236",
        "surface-dim": "#d8dadc",
        "outline": "#777587",
        "background": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "on-secondary-container": "#54647a",
        "primary-fixed-dim": "#c3c0ff",
        "on-surface-variant": "#464555",
        "secondary": "#505f76",
        "on-primary-fixed": "#0f0069",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed-dim": "#b7c8e1",
        "on-primary-container": "#dad7ff",
        "inverse-primary": "#c3c0ff",
        "inverse-surface": "#2d3133",
        "tertiary": "#005338"
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
        sans: ["Inter", "sans-serif"],
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
      boxShadow: {
        'glass': '0 10px 30px -5px rgba(25, 28, 30, 0.04)',
      }
    },
  },
  plugins: [],
}
