import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    'Français (France)': {
        'app_name': 'Gestion de la Coopération - UIDT',
        'institutional_sub': 'Université Iba Der Thiam de Thiès',
        'dashboard': 'Tableau de bord',
        'conventions': 'Projets de Coopération',
        'validation': 'Dossiers en Validation',
        'timeline': 'Fil d’Activité (Audit)',
        'indicators': 'Aide à la Décision (KPI)',
        'settings': 'Configuration',
        'archived': 'Archives',
        'logout': 'Se déconnecter',
        'search': 'Rechercher un dossier...',
        'active_session': 'Session Active',
        'chief_curator': 'Administrateur Principal',
        'role_admin': 'Administrateur Principal',
        'role_responsable': 'Responsable',
        'role_porteur_projet': 'Porteur de Projet',
        'role_directeur_cooperation': 'Directeur de Coopération',
        'role_recteur': 'Recteur',
        'role_partenaire': 'Partenaire Stratégique',
        'nouvelle_convention': 'Nouvelle-Convention',
        'ouvrir_ticket': 'Ouvrir-un-ticket',
        
        // Validation / Submission Page
        'submit_project': 'Soumettre un Projet',
        'draft_saved': 'Brouillon enregistré il y a {time}',
        'identity': 'Identité',
        'strategy': 'Stratégie',
        'documents': 'Pièces Jointes',
        'project_identity': 'Identité du Projet',
        'institutional_data': 'Données institutionnelles de base',
        'academic_project_title': 'Titre du projet académique',
        'partner_institution': 'Institution partenaire',
        'cooperation_type': 'Type de coopération',
        'strategic_details': 'Détails Stratégiques',
        'objectives_impact': 'Objectifs et Impact National',
        'institutional_objectives': 'Objectifs institutionnels',
        'main_activities': 'Activités principales',
        'attached_files': 'Pièces Jointes',
        'mandatory_docs': 'Documentation obligatoire',
        'drop_files_here': 'Déposer les documents ici',
        'browse_files': 'Parcourir les fichiers',
        'delete_draft': 'Effacer le brouillon',
        'save_draft': 'Sauvegarder',
        'submit_final': 'Soumettre le Projet',
        
        // Right Sidebar Guide
        'submission_guide': 'Guide de Soumission',
        'strategic_eligibility': 'Éligibilité Stratégique',
        'eligibility_desc': 'Le projet doit s’aligner sur au moins deux piliers de notre plan quinquennal.',
        'mandatory_docs_list': 'Documents Obligatoires',
        'validation_delays': 'Délais de Validation',
        'delays_desc': 'Le comité d’éthique se réunit tous les premiers mardis du mois.',
        'need_help': 'Besoin d’assistance ?',
        'contact_office': 'Contactez le bureau des affaires globales au poste 4421.',
        'contact_support': 'Contacter le support',
        'archive_status': 'Statut de l’Archive',
        'archive_desc': 'Vous avez {pending} projets en validation et {active} archives actives.',
        'consult_kpi': 'Consulter les KPI',
        
        // Statuses
        'status_brouillon': 'Brouillon',
        'status_soumis': 'Soumis',
        'status_valide_dir': 'Validé par la Direction',
        'status_signe_recteur': 'Signé par le Recteur',
        'status_rejete': 'Rejeté',
        
        // Institutional Table Fields
        'num_short': 'N°',
        'partner_type': 'Type de Partenaire',
        'year': 'Année',
        'duration': 'Durée',
        'indicator_performance': 'Indicateur de Performance',
        'target': 'Cible',
        'actual_value': 'Valeur',
        'completion_rate': 'Taux de réalisation (%)',
        'observations': 'Observations',
        'project_title_short': 'Titre du projet / Convention',
        
        // General
        'loading': 'Chargement...',
        'save': 'Sauvegarder',
        'cancel': 'Annuler',
        'edit': 'Modifier',
    },
    'English (US)': {
        'app_name': 'Cooperation Management - UIDT',
        'institutional_sub': 'Iba Der Thiam University of Thiès',
        'dashboard': 'Dashboard',
        'conventions': 'Cooperation Projects',
        'validation': 'Validation Dossiers',
        'timeline': 'Activity Feed (Audit)',
        'indicators': 'Decision Support (KPI)',
        'settings': 'Settings',
        'archived': 'Archives',
        'logout': 'Logout',
        'search': 'Search archive...',
        'active_session': 'Active Session',
        'chief_curator': 'Chief Administrator',
        'role_admin': 'Chief Administrator',
        'role_responsable': 'Manager',
        'role_porteur_projet': 'Project Lead',
        'role_directeur_cooperation': 'Cooperation Director',
        'role_recteur': 'Rector',
        'role_partenaire': 'Strategic Partner',
        'nouvelle_convention': 'New-Convention',
        'ouvrir_ticket': 'Open-a-ticket',
        
        // Validation / Submission Page
        'submit_project': 'Submit Project',
        'draft_saved': 'Draft saved {time} ago',
        'identity': 'Identity',
        'strategy': 'Strategy',
        'documents': 'Documents',
        'project_identity': 'Project Identity',
        'institutional_data': 'Basic institutional data',
        'academic_project_title': 'Academic project title',
        'partner_institution': 'Partner institution',
        'cooperation_type': 'Cooperation type',
        'strategic_details': 'Strategic Details',
        'objectives_impact': 'Objectives & National Impact',
        'institutional_objectives': 'Institutional objectives',
        'main_activities': 'Main activities',
        'attached_files': 'Attached Files',
        'mandatory_docs': 'Mandatory documentation',
        'drop_files_here': 'Drop files here',
        'browse_files': 'Browse files',
        'delete_draft': 'Delete draft',
        'save_draft': 'Save',
        'submit_final': 'Submit Project',
        
        // Right Sidebar Guide
        'submission_guide': 'Submission Guide',
        'strategic_eligibility': 'Strategic Eligibility',
        'eligibility_desc': 'The project must align with at least two pillars of our 5-year plan.',
        'mandatory_docs_list': 'Mandatory Documents',
        'validation_delays': 'Validation Delays',
        'delays_desc': 'The ethics committee meets every first Tuesday of the month.',
        'need_help': 'Need assistance?',
        'contact_office': 'Contact the global affairs office at extension 4421.',
        'contact_support': 'Contact support',
        'archive_status': 'Archive Status',
        'archive_desc': 'You have {pending} projects in validation and {active} active archives.',
        'consult_kpi': 'Consult KPIs',
        
        // Statuses
        'status_brouillon': 'Draft',
        'status_soumis': 'Submitted',
        'status_valide_dir': 'Director Validated',
        'status_signe_recteur': 'Rector Signed',
        'status_rejete': 'Rejected',

        // Institutional Table Fields
        'num_short': 'No.',
        'partner_type': 'Partner Type',
        'year': 'Year',
        'duration': 'Duration',
        'indicator_performance': 'Performance Indicator',
        'target': 'Target',
        'actual_value': 'Actual Value',
        'completion_rate': 'Completion Rate (%)',
        'observations': 'Observations',
        'project_title_short': 'Project Title / Convention',
        
        // General
        'loading': 'Loading...',
        'save': 'Save',
        'cancel': 'Cancel',
        'edit': 'Edit',
    },
    'Español': {
        'dashboard': 'Tablero',
        'conventions': 'Convenciones',
        'settings': 'Ajustes',
        'logout': 'Cerrar sesión',
        'partner_page': 'Mi Página',
        'notifications': 'Notificaciones',
        'all_conventions': 'Todas las Convenciones',
        'pending_conventions': 'Convenciones Pendientes',
        'active_conventions': 'Convenciones Activas',
        'completed_conventions': 'Convenciones Terminadas',
        'no_notifications': 'Sin notificaciones',
        'change_password': 'Cambiar Contraseña',
        'language': 'Idioma',
        'dark_mode': 'Modo Oscuro',
        'profile': 'Perfil',
        'save': 'Guardar',
        'cancel': 'Cancelar',
        'edit': 'Editar',
        'welcome': 'Bienvenido',
        'stats': 'Estadísticas',
        'quick_actions': 'Acciones Rápidas',
        'total': 'Total',
        'active': 'Activo',
        'pending': 'Pendiente',
        'completed': 'Terminado',
        'search': 'Buscar...',
        'notifications_pending': 'Tienes {count} expedientes pendientes',
        'login': 'Iniciar sesión',
        'register': 'Registrarse',
        'email': 'Correo electrónico',
        'password': 'Contraseña',
        'confirm_password': 'Confirmar contraseña',
        'name': 'Nombre completo',
        'role': 'Rol',
        'create_account': 'Crear cuenta',
        'already_have_account': '¿Ya tienes una cuenta?',
        'no_account': '¿Aún no tienes cuenta?',
        'indicators': 'Indicadores',
        'overview': 'Resumen',
        'performance_overview': 'Seguimiento analítico y rendimiento de convenciones activas.',
        'export': 'Exportar',
        'nouvelle_convention': 'Nueva Convención',
        'ouvrir_ticket': 'Abrir-un-ticket',
        'num_conventions': 'Número de Convenciones',
        'avg_kpi': 'KPI Promedio',
        'active_partners': 'Socios Activos',
        'vs_last_month': 'vs mes anterior',
        'global_performance': 'rendimiento global',
        'new_this_semester': 'Nuevos este semestre',
        'kpi_evolution': 'Evolución Global de KPI',
        'aggregated_performance': 'Rendimiento agregado en los últimos 12 meses',
        'convention_status_dist': 'Estado de la Convención',
        'distribution_by_status': 'Distribución por estado de progreso',
        'q4_objectives': 'Objetivos Q4',
        'on_track': 'En camino',
        'pending_attention': 'La convención "{name}" requiere su atención.',
        'all_dossiers': 'Ver todos los expedientes',
        'loading': 'Cargando...',
    },
    'Deutsch': {
        'dashboard': 'Dashboard',
        'conventions': 'Konventionen',
        'settings': 'Einstellungen',
        'logout': 'Abmelden',
        'partner_page': 'Meine Seite',
        'notifications': 'Benachrichtigungen',
        'all_conventions': 'Alle Konventionen',
        'pending_conventions': 'Ausstehende Konventionen',
        'active_conventions': 'Aktive Konventionen',
        'completed_conventions': 'Abgeschlossene Konventionen',
        'no_notifications': 'Keine Benachr.',
        'change_password': 'Passwort ändern',
        'language': 'Sprache',
        'dark_mode': 'Dunkelmodus',
        'profile': 'Profil',
        'save': 'Speichern',
        'cancel': 'Abbrechen',
        'edit': 'Bearbeiten',
        'welcome': 'Willkommen',
        'stats': 'Statistiken',
        'quick_actions': 'Schnellaktionen',
        'total': 'Gesamt',
        'active': 'Aktiv',
        'pending': 'Ausstehend',
        'completed': 'Abgeschlossen',
        'search': 'Suchen...',
        'notifications_pending': 'Sie haben {count} ausstehende Dossiers',
        'login': 'Anmelden',
        'register': 'Registrieren',
        'email': 'E-Mail',
        'password': 'Passwort',
        'confirm_password': 'Passwort bestätigen',
        'name': 'Vollständiger Name',
        'role': 'Rolle',
        'create_account': 'Konto erstellen',
        'already_have_account': 'Bereits ein Konto?',
        'no_account': 'Noch kein Konto?',
        'indicators': 'Indikatoren',
        'overview': 'Übersicht',
        'performance_overview': 'Analytische Verfolgung und Leistung aktiver Konventionen.',
        'export': 'Exportieren',
        'nouvelle_convention': 'Neue Konvention',
        'ouvrir_ticket': 'Ticket-eröffnen',
        'num_conventions': 'Anzahl der Konventionen',
        'avg_kpi': 'Durchschnittlicher KPI',
        'active_partners': 'Aktive Partner',
        'vs_last_month': 'vs Letzter Monat',
        'global_performance': 'Gesamtleistung',
        'new_this_semester': 'Neu in diesem Semester',
        'kpi_evolution': 'Globale KPI-Entwicklung',
        'aggregated_performance': 'Aggregierte Leistung der letzten 12 Monate',
        'convention_status_dist': 'Konventionsstatus',
        'distribution_by_status': 'Verteilung nach Fortschrittsstatus',
        'q4_objectives': 'Q4 Ziele',
        'on_track': 'Auf Kurs',
        'pending_attention': 'Die Konvention "{name}" erfordert Ihre Aufmerksamkeit.',
        'all_dossiers': 'Alle Dossiers anzeigen',
        'loading': 'Laden...',
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'Français (France)');

    const t = (key, params = {}) => {
        let text = translations[language]?.[key] || translations['Français (France)'][key] || key;
        
        Object.keys(params).forEach(param => {
            text = text.replace(`{${param}}`, params[param]);
        });
        
        return text;
    };

    const changeLanguage = (newLang) => {
        setLanguage(newLang);
        localStorage.setItem('language', newLang);
    };

    return (
        <LanguageContext.Provider value={{ language, t, changeLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
