import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    'Français (France)': {
        'dashboard': 'Tableau de bord',
        'conventions': 'Conventions',
        'settings': 'Paramètres',
        'logout': 'Se déconnecter',
        'partner_page': 'Ma Page',
        'notifications': 'Notifications',
        'all_conventions': 'Toutes les conventions',
        'pending_conventions': 'Conventions en attente',
        'active_conventions': 'Conventions actives',
        'completed_conventions': 'Conventions terminées',
        'no_notifications': 'Aucune notification',
        'change_password': 'Changer le mot de passe',
        'language': 'Langue',
        'dark_mode': 'Mode Sombre',
        'profile': 'Profil',
        'save': 'Sauvegarder',
        'cancel': 'Annuler',
        'edit': 'Modifier',
        'welcome': 'Bienvenue',
        'stats': 'Statistiques',
        'quick_actions': 'Actions Rapides',
        'total': 'Total',
        'active': 'En cours',
        'pending': 'En attente',
        'completed': 'Terminées',
        'search': 'Rechercher...',
        'notifications_pending': 'Vous avez {count} dossiers en attente',
        'login': 'Se connecter',
        'register': 'S\'inscrire',
        'email': 'Email',
        'password': 'Mot de passe',
        'confirm_password': 'Confirmer le mot de passe',
        'name': 'Nom Complet',
        'role': 'Rôle',
        'create_account': 'Créer mon compte',
        'already_have_account': 'Déjà un compte ?',
        'no_account': 'Pas encore de compte ?',
        'indicators': 'Indicateurs',
        'overview': 'Vue d’ensemble',
        'performance_overview': 'Suivi analytique et performance des conventions actives.',
        'export': 'Exporter',
        'new_convention': 'Nouvelle Convention',
        'num_conventions': 'Nombre de conventions',
        'avg_kpi': 'Moyenne des KPI',
        'active_partners': 'Partenaires actifs',
        'vs_last_month': 'vs mois dernier',
        'global_performance': 'performance globale',
        'new_this_semester': 'Nouveaux ce semestre',
        'kpi_evolution': 'Évolution globale des KPI',
        'aggregated_performance': 'Performance agrégée sur les 12 derniers mois',
        'convention_status_dist': 'Statut des conventions',
        'distribution_by_status': 'Répartition par état d’avancement',
        'q4_objectives': 'Objectifs Q4',
        'on_track': 'En bonne voie',
        'pending_attention': 'La convention "{name}" nécessite votre attention.',
        'all_dossiers': 'Consulter tous les dossiers',
        'loading': 'Chargement...',
    },
    'English (US)': {
        'dashboard': 'Dashboard',
        'conventions': 'Conventions',
        'settings': 'Settings',
        'logout': 'Logout',
        'partner_page': 'My Page',
        'notifications': 'Notifications',
        'all_conventions': 'All Conventions',
        'pending_conventions': 'Pending Conventions',
        'active_conventions': 'Active Conventions',
        'completed_conventions': 'Completed Conventions',
        'no_notifications': 'No notifications',
        'change_password': 'Change Password',
        'language': 'Language',
        'dark_mode': 'Dark Mode',
        'profile': 'Profile',
        'save': 'Save',
        'cancel': 'Cancel',
        'edit': 'Edit',
        'welcome': 'Welcome',
        'stats': 'Statistics',
        'quick_actions': 'Quick Actions',
        'total': 'Total',
        'active': 'Active',
        'pending': 'Pending',
        'completed': 'Completed',
        'search': 'Search...',
        'notifications_pending': 'You have {count} pending dossiers',
        'login': 'Login',
        'register': 'Register',
        'email': 'Email',
        'password': 'Password',
        'confirm_password': 'Confirm Password',
        'name': 'Full Name',
        'role': 'Role',
        'create_account': 'Create Account',
        'already_have_account': 'Already have an account?',
        'no_account': 'No account yet?',
        'indicators': 'Indicators',
        'overview': 'Overview',
        'performance_overview': 'Analytical tracking and performance of active conventions.',
        'export': 'Export',
        'new_convention': 'New Convention',
        'num_conventions': 'Number of Conventions',
        'avg_kpi': 'Average KPI',
        'active_partners': 'Active Partners',
        'vs_last_month': 'vs last month',
        'global_performance': 'global performance',
        'new_this_semester': 'New this semester',
        'kpi_evolution': 'Global KPI Evolution',
        'aggregated_performance': 'Aggregated performance over the last 12 months',
        'convention_status_dist': 'Convention Status',
        'distribution_by_status': 'Distribution by progress state',
        'q4_objectives': 'Q4 Objectives',
        'on_track': 'On track',
        'pending_attention': 'The convention "{name}" requires your attention.',
        'all_dossiers': 'View all dossiers',
        'loading': 'Loading...',
    },
    'Español': {
        'dashboard': 'Tablero',
        'conventions': 'Convenciones',
        'settings': 'Ajustes',
        'logout': 'Cerrar sesión',
        'partner_page': 'Mi Página',
        'notifications': 'Notificaciones',
        'all_conventions': 'Todas las Convenciones',
        'pending_conventions': 'Convenciones Pendientes',
        'active_conventions': 'Convenciones Activas',
        'completed_conventions': 'Convenciones Terminadas',
        'no_notifications': 'Sin notificaciones',
        'change_password': 'Cambiar Contraseña',
        'language': 'Idioma',
        'dark_mode': 'Modo Oscuro',
        'profile': 'Perfil',
        'save': 'Guardar',
        'cancel': 'Cancelar',
        'edit': 'Editar',
        'welcome': 'Bienvenido',
        'stats': 'Estadísticas',
        'quick_actions': 'Acciones Rápidas',
        'total': 'Total',
        'active': 'Activo',
        'pending': 'Pendiente',
        'completed': 'Terminado',
        'search': 'Buscar...',
        'notifications_pending': 'Tienes {count} expedientes pendientes',
        'login': 'Iniciar sesión',
        'register': 'Registrarse',
        'email': 'Correo electrónico',
        'password': 'Contraseña',
        'confirm_password': 'Confirmar contraseña',
        'name': 'Nombre completo',
        'role': 'Rol',
        'create_account': 'Crear cuenta',
        'already_have_account': '¿Ya tienes una cuenta?',
        'no_account': '¿Aún no tienes cuenta?',
        'indicators': 'Indicadores',
        'overview': 'Resumen',
        'performance_overview': 'Seguimiento analítico y rendimiento de convenciones activas.',
        'export': 'Exportar',
        'new_convention': 'Nueva Convención',
        'num_conventions': 'Número de Convenciones',
        'avg_kpi': 'KPI Promedio',
        'active_partners': 'Socios Activos',
        'vs_last_month': 'vs mes anterior',
        'global_performance': 'rendimiento global',
        'new_this_semester': 'Nuevos este semestre',
        'kpi_evolution': 'Evolución Global de KPI',
        'aggregated_performance': 'Rendimiento agregado en los últimos 12 meses',
        'convention_status_dist': 'Estado de la Convención',
        'distribution_by_status': 'Distribución por estado de progreso',
        'q4_objectives': 'Objetivos Q4',
        'on_track': 'En camino',
        'pending_attention': 'La convención "{name}" requiere su atención.',
        'all_dossiers': 'Ver todos los expedientes',
        'loading': 'Cargando...',
    },
    'Deutsch': {
        'dashboard': 'Dashboard',
        'conventions': 'Konventionen',
        'settings': 'Einstellungen',
        'logout': 'Abmelden',
        'partner_page': 'Meine Seite',
        'notifications': 'Benachrichtigungen',
        'all_conventions': 'Alle Konventionen',
        'pending_conventions': 'Ausstehende Konventionen',
        'active_conventions': 'Aktive Konventionen',
        'completed_conventions': 'Abgeschlossene Konventionen',
        'no_notifications': 'Keine Benachr.',
        'change_password': 'Passwort ändern',
        'language': 'Sprache',
        'dark_mode': 'Dunkelmodus',
        'profile': 'Profil',
        'save': 'Speichern',
        'cancel': 'Abbrechen',
        'edit': 'Bearbeiten',
        'welcome': 'Willkommen',
        'stats': 'Statistiken',
        'quick_actions': 'Schnellaktionen',
        'total': 'Gesamt',
        'active': 'Aktiv',
        'pending': 'Ausstehend',
        'completed': 'Abgeschlossen',
        'search': 'Suchen...',
        'notifications_pending': 'Sie haben {count} ausstehende Dossiers',
        'login': 'Anmelden',
        'register': 'Registrieren',
        'email': 'E-Mail',
        'password': 'Passwort',
        'confirm_password': 'Passwort bestätigen',
        'name': 'Vollständiger Name',
        'role': 'Rolle',
        'create_account': 'Konto erstellen',
        'already_have_account': 'Bereits ein Konto?',
        'no_account': 'Noch kein Konto?',
        'indicators': 'Indikatoren',
        'overview': 'Übersicht',
        'performance_overview': 'Analytische Verfolgung und Leistung aktiver Konventionen.',
        'export': 'Exportieren',
        'new_convention': 'Neue Konvention',
        'num_conventions': 'Anzahl der Konventionen',
        'avg_kpi': 'Durchschnittlicher KPI',
        'active_partners': 'Aktive Partner',
        'vs_last_month': 'vs Letzter Monat',
        'global_performance': 'Gesamtleistung',
        'new_this_semester': 'Neu in diesem Semester',
        'kpi_evolution': 'Globale KPI-Entwicklung',
        'aggregated_performance': 'Aggregierte Leistung der letzten 12 Monate',
        'convention_status_dist': 'Konventionsstatus',
        'distribution_by_status': 'Verteilung nach Fortschrittsstatus',
        'q4_objectives': 'Q4 Ziele',
        'on_track': 'Auf Kurs',
        'pending_attention': 'Die Konvention "{name}" erfordert Ihre Aufmerksamkeit.',
        'all_dossiers': 'Alle Dossiers anzeigen',
        'loading': 'Laden...',
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'Français (France)');

    const t = (key, params = {}) => {
        let text = translations[language]?.[key] || translations['Français (France)'][key] || key;
        
        Object.keys(params).forEach(param => {
            text = text.replace(`{${param}}`, params[param]);
        });
        
        return text;
    };

    const changeLanguage = (newLang) => {
        setLanguage(newLang);
        localStorage.setItem('language', newLang);
    };

    return (
        <LanguageContext.Provider value={{ language, t, changeLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
